Add make_response function
edmondchuc/flask-htmx pull request #17
Opened 2022-11-19 23:41 UTC by sponsfreixes

This PR adds a new function, `make_response`, that works like Flask's `make_response` but with extra arguments to help setting htmx headers in a pythonic way.

It includes updates tests for 100% coverage, and README.rst and Sphinx documentation.

2022-11-21 05:08 UTC, edmondchuc requested changes
A few copy and paste issues but otherwise looks good.

2022-11-21 05:08 UTC, edmondchuc commented on README.rst
> +Use :code:`htmx_flask.make_response` for that. For example, instead of:
```suggestion
Use :code:`flask_htmx.make_response` for that. For example, instead of:
```

2022-11-21 05:08 UTC, edmondchuc commented on README.rst
> +    from htmx_flask import make_response
```suggestion
    from flask_htmx import make_response
```

2022-11-21 17:21 UTC, sponsfreixes commented
> A few copy and paste issues but otherwise looks good.

🤦 

Fixed!

2022-11-23 00:03 UTC, edmondchuc approved these changes

2022-11-23 01:42 UTC, merged